#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	3) notify-send "🖥 CPU module " "\- Shows CPUutilization.
- Click to show intensive processes.
- % is of single core." ;;
esac

CPU_IDLE=$(sar -u 1 3 | # Get CPU usage percentage (sampled once every 3 seconds)
	tail -n 1 | # And only retrieve the last line
	tr -s ' ' | # Replace all whitespaces with one for separator (since output is not using Tab, and variable spaces)
	cut -d" " -f8 # Retrieve only the last field which is CPU Usage %
)

CPU_USED=$(echo "100 - $CPU_IDLE" | bc)
echo "$CPU_USED%"
